# Generated by Django 4.1.7 on 2023-03-19 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiki_title', models.TextField()),
                ('target_lang', models.CharField(choices=[('Bengali', 'bn'), ('Gujarati', 'gu'), ('Hindi', 'hi'), ('Kannada', 'kn'), ('Malayalam', 'ml'), ('Marathi', 'mr'), ('Nepali', 'ne'), ('Oriya', 'or'), ('Punjabi', 'pa'), ('Sinhala', 'si'), ('Tamil', 'ta'), ('Telugu', 'te'), ('Urdu', 'ur')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_sentence', models.TextField()),
                ('translated_sentence', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translate_app.project')),
            ],
        ),
    ]
