# Generated by Django 4.1.7 on 2023-03-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='translated_sentence',
            field=models.TextField(blank=True, null=True),
        ),
    ]
