# Generated by Django 4.1.7 on 2023-03-20 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('translate_app', '0002_alter_sentence_translated_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='annotator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='annotated_projects', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='target_lang',
            field=models.CharField(choices=[('Bengali', 'bengali'), ('Gujarati', 'gujarati'), ('Hindi', 'hindi'), ('Kannada', 'kannada'), ('Malayalam', 'malayalam'), ('Marathi', 'marathi'), ('Nepali', 'nepali'), ('Oriya', 'oriya'), ('Punjabi', 'punjabi'), ('Sinhala', 'sinhala'), ('Tamil', 'tamil'), ('Telugu', 'telugu'), ('Urdu', 'urdu')], max_length=30),
        ),
    ]
