# Generated by Django 4.1.7 on 2023-03-20 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('translate_app', '0003_project_annotator_project_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='annotator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotated_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
